### PR TITLE
Replace with the Turtlebot Gazebo bag for full coverage, except for /camera* topics

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by 130s** [comment]
As discussed in https://github.com/ros-perception/slam_gmapping/pull/35#issuecomment-122597312

**Comment by 130s** [comment]
Ping @vrabaud since in your PR https://github.com/ros-perception/slam_gmapping/pull/35 you need a bag file that contain `scan` and `tf`([in this line](https://github.com/ros-perception/slam_gmapping/pull/35/files#diff-59ff1080d7d129db69f79b16e28ea45dR63)).

**Comment by vrabaud** [comment]
thx, data is good but the robot does not move so I cannot test the result :(

**Comment by 130s** [comment]
Sorry! Now bag file is updated.

**Comment by 130s** [comment]
@Tones29 your map in https://github.com/ros-perception/slam_gmapping/issues/35 looks far more appropriate. Would you mind opening a pull request using that file? I close this.

**Comment by Tones29** [comment]
Hi Isaac, I am currently very busy, but will open the PR for the map
in two weeks.

Best, Andi

**Comment by vrabaud** [comment]
@Tones29 , I did push your data to that repo, and created a test from it so we're all good. Thx.

**Comment by Tones29** [comment]
Thank you, @vrabaud and @130s

**Pull request closed without merging**
